theme: minima
title: Community CollabBlog
author: https://github.com/ThesllaDev
email: ThesllaDev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An amazing collaboration blog made by the community for the community
# social links
github_username: https://github.com/ThesllaDev # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
